### ISSUE TITLE
could not find package krytonit3/pusher at any version for you minimum stability(stable)

### ISSUE THREAD

**Issue by minhloc0304** [Kryptonit3/Pusher#1]
I tried to install using the composer but the error says "could not find package krytonit3/pusher at any version for you minimum stability(stable). Check the package spelling or your minimum stabilty." Do you have any idea about this?

**Comment by Kryptonit3-zz** [comment]
@minhloc0304 are you using L5.1?

**Comment by minhloc0304** [comment]
@Kryptonit3 I' m using Laravel 5.0

**Comment by Kryptonit3-zz** [comment]
For now, just add this to your `composer.json` file in the `"require"` section

```
"kryptonit3/pusher": "dev-master"
```

or run

```
composer require kryptonit3/pusher:dev-master
```

I will update docs.

Thanks!

**Comment by Kryptonit3-zz** [comment]
@minhloc0304 did that work for you?

**Comment by minhloc0304** [comment]
@Kryptonit3 Yes, It worked now :+1: 
Thanks !!
